#  common configurations between all environments
version: '3.6'
services:
  web:
    build:
      context: ./web/
      args: # pass env vars from .env file to Dockerfile
        - WEB_SERVICE_BASE_IMG_TAG=${WEB_SERVICE_BASE_IMG_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: static_root_deploy_folder
        target: /public/
        read_only: true
    depends_on:
      - app
      #- db
  app:
    build:
      context: ./app/
      args: # pass env vars from .env file to Dockerfile
        - APP_SERVICE_BASE_IMG_TAG=${APP_SERVICE_BASE_IMG_TAG}
        - APP_SERVICE_ROOT_DIR=${APP_SERVICE_ROOT_DIR}
        - DJANGO_PROJECT_NAME=${DJANGO_PROJECT_NAME}
    environment: # pass env var from .env file to container
      - APP_SERVICE_ROOT_DIR=${APP_SERVICE_ROOT_DIR}
      - DJANGO_PROJECT_NAME=${DJANGO_PROJECT_NAME}
      - STATIC_ROOT_FOLDER_NAME=${STATIC_ROOT_FOLDER_NAME}
    volumes:
      - type: volume
        source: static_root_deploy_folder
        target: ${APP_SERVICE_ROOT_DIR}/${STATIC_ROOT_FOLDER_NAME}/
    depends_on:
      - worker
  worker:
    build:
      context: ./worker/
  db:
    build:
      context: ./db/

volumes:
  static_root_deploy_folder:
